// <auto-generated />
namespace UPTax.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TOtalBuildingHouses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TOtalBuildingHouses));
        
        string IMigrationMetadata.Id
        {
            get { return "202103170838369_TOtalBuildingHouses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
