// <auto-generated />
namespace UPTax.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class alter_AdminNotice_Add_date : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_AdminNotice_Add_date));
        
        string IMigrationMetadata.Id
        {
            get { return "202105290505250_alter_AdminNotice_Add_date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
