// <auto-generated />
namespace UPTax.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FinancialYear_and_TaxGenerateInfo_tbl_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FinancialYear_and_TaxGenerateInfo_tbl_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202103190856430_FinancialYear_and_TaxGenerateInfo_tbl_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
